name: 'Wait For Required Status Checks'
description: "Wait for a repo's required status checks to complete"
author: 'Armory'
inputs:
  token:
    description: 'The GitHub token to use for making API requests.'
    required: true
  pull_request_number: 
    required: true
  timeoutSeconds:
    description: 'The number of seconds to wait for the check to complete.'
  intervalSeconds:
    description: 'The number of seconds to wait before each poll of the GitHub API.'
runs:
  using: 'node12'
  main: 'dist/index.js'
