name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run test
      - run: |
          npm run build && npm run package
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: commit build to dist/
          branch: master
          file_pattern: dist/*.js
